BEGIN;
ALTER TYPE "DriveFolderPurpose" ADD VALUE IF NOT EXISTS 'EXPENSES';
ALTER TYPE "DriveFolderPurpose" ADD VALUE IF NOT EXISTS 'INCOME';
ALTER TYPE "DriveFolderPurpose" ADD VALUE IF NOT EXISTS 'PERMISSIONS';
ALTER TYPE "DriveFolderPurpose" ADD VALUE IF NOT EXISTS 'MEDIA';
COMMIT;
